import { GARAGE_PARTS, loadGarageSetup, saveGarageSetup, setupEffects } from "./garage-setup.js";
import { createShowroom } from "./showroom.js";
let setup=loadGarageSetup();
const { car } = createShowroom(document.getElementById("garage-canvas"));
function applyVisual(){const fw=car.getObjectByName("frontWing"),rw=car.getObjectByName("rearWing");if(fw)fw.rotation.x=setup.frontWing==="high"?-.16:setup.frontWing==="low"?.08:-.05;if(rw){rw.position.y=setup.rearWing==="high"?1.08:setup.rearWing==="low"?.86:.95;rw.rotation.x=setup.rearWing==="high"?-.18:setup.rearWing==="low"?.08:0}}
const labels={speed:"Velocità",downforce:"Carico",braking:"Frenata",stability:"Stabilità",traction:"Trazione"};
function renderUI(){const effects=setupEffects(setup),base={speed:50,downforce:50,braking:50,stability:50,traction:50};document.getElementById("garage-stats").innerHTML=Object.entries(base).map(([k,v])=>`<div><span>${labels[k]}</span><div><i style="width:${Math.max(10,Math.min(90,v+(effects[k]||0)*7))}%"></i></div></div>`).join("");document.getElementById("garage-parts").innerHTML=Object.entries(GARAGE_PARTS).map(([part,data])=>`<section class="garage-part"><h2>${data.label}</h2><div>${Object.entries(data.variants).map(([id,v])=>`<button draggable="true" data-part="${part}" data-id="${id}" aria-pressed="${setup[part]===id}" class="${setup[part]===id?"active":""}">${v.label}</button>`).join("")}</div></section>`).join("");document.querySelectorAll(".garage-mount").forEach(z=>z.classList.toggle("installed",!!setup[z.dataset.part]));applyVisual()}
function mount(part,id){if(!GARAGE_PARTS[part]?.variants[id])return;setup[part]=id;saveGarageSetup(setup);renderUI();const z=document.querySelector(`.garage-mount[data-part="${part}"]`);if(z){z.classList.add("just-mounted");setTimeout(()=>z.classList.remove("just-mounted"),650)}document.getElementById("garage-status").textContent=`${GARAGE_PARTS[part].label}: ${GARAGE_PARTS[part].variants[id].label} montato.`}
document.getElementById("garage-parts").addEventListener("dragstart",e=>{const b=e.target.closest("[data-part]");if(!b)return;e.dataTransfer.setData("text/plain",JSON.stringify({part:b.dataset.part,id:b.dataset.id}));document.body.dataset.dragPart=b.dataset.part;document.getElementById("garage-status").textContent=`Trascina ${GARAGE_PARTS[b.dataset.part].label} sulla zona evidenziata della monoposto.`});
document.getElementById("garage-parts").addEventListener("dragend",()=>{delete document.body.dataset.dragPart});
document.getElementById("garage-parts").addEventListener("click",e=>{const b=e.target.closest("[data-part]");if(b)mount(b.dataset.part,b.dataset.id)});
document.querySelectorAll(".garage-mount").forEach(zone=>{zone.addEventListener("dragover",e=>{e.preventDefault();if(document.body.dataset.dragPart===zone.dataset.part)zone.classList.add("over")});zone.addEventListener("dragleave",()=>zone.classList.remove("over"));zone.addEventListener("drop",e=>{e.preventDefault();zone.classList.remove("over");try{const d=JSON.parse(e.dataTransfer.getData("text/plain"));if(d.part===zone.dataset.part)mount(d.part,d.id);else document.getElementById("garage-status").textContent="Questo componente va montato sulla zona con lo stesso nome."}catch(_){}})});

renderUI();
