// Usage: BROWSER_BIN=/path/to/chrome THREE_MODULE=/path/to/three-r160.mjs
// NODE_PATH=/path/to/playwright/node_modules node tests/browser-smoke.cjs
// CDN interception serves the exact downloaded r160 module. Test-only probes
// are appended by the HTTP server; shipped sources do not contain test hooks.
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const root=path.resolve(__dirname,'..'),out=process.env.SMOKE_OUTPUT||'/tmp';
const server=http.createServer((req,res)=>{let p=root+req.url.split('?')[0];if(p.endsWith('/'))p+='index.html';try{let data=fs.readFileSync(p);res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');if(p.endsWith('/main.js'))data+='\nglobalThis.__probe=()=>({speed:state.speed,heading:state.heading,yaw:state.yawRate,touchSteer,filteredSteer,wheelPointer,input:{...input},raceState,sessionPhase,qualiState,draws:renderer.info.render.calls});';res.end(data);}catch(e){res.statusCode=404;res.end();}}).listen(8001,'127.0.0.1');
(async()=>{const browser=await chromium.launch({executablePath:process.env.BROWSER_BIN,headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
const errors=[],ctx=await browser.newContext({viewport:{width:1000,height:650},deviceScaleFactor:1,hasTouch:true});
await ctx.route('https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js',r=>r.fulfill({path:process.env.THREE_MODULE,contentType:'application/javascript'}));const page=await ctx.newPage();page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('CONSOLE',m.text())}});
if (!process.env.SKIP_GARAGE) { await page.goto('http://127.0.0.1:8001/games/f1-racer/garage.html');await page.waitForTimeout(800);
await page.setViewportSize({width:390,height:844});await page.locator('#garage-parts button[data-part="suspension"][data-id="stiff"]').tap();let c=await page.locator('#garage-canvas').boundingBox();assert(c.width>350&&c.height>180&&c.y>=0&&c.y+c.height<844);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('f1racer-garage-v1')).suspension),'stiff');await page.screenshot({path:path.join(out,'garage-mobile.png')});console.log('PASS persistent portrait preview and suspension selection');
await page.setViewportSize({width:844,height:390});await page.locator('#garage-parts button[data-part="brakes"][data-id="aggressive"]').tap();c=await page.locator('#garage-canvas').boundingBox();assert(c.width>350&&c.height>150&&c.y+c.height<390);await page.screenshot({path:path.join(out,'garage-landscape.png')});console.log('PASS persistent landscape preview'); }
await page.setViewportSize({width:1000,height:650});await page.goto('http://127.0.0.1:8001/games/f1-racer/race.html?touch=1');await page.waitForFunction(()=>window.__probe&&__probe().qualiState==='running',null,{timeout:60000});await page.screenshot({path:path.join(out,'race-dry.png')});console.log('Dry',await page.evaluate(()=>__probe()));if(process.env.CAPTURE_ONLY){assert.deepEqual(errors,[]);return;}
const wheel=await page.locator('#wheel-control').boundingBox(),gas=await page.locator('#btn-gas').boundingBox(),session=await ctx.newCDPSession(page);
const w={x:Math.round(wheel.x+wheel.width/2),y:Math.round(wheel.y+wheel.height/2),id:1},g={x:Math.round(gas.x+gas.width/2),y:Math.round(gas.y+gas.height/2),id:2};
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[w,g]});await page.waitForTimeout(100);let p=await page.evaluate(()=>__probe());assert.equal(p.touchSteer,0);assert(p.input.forward);console.log('PASS first contact neutral and gas held');
await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...w,x:w.x+40},g]});await page.waitForTimeout(200);p=await page.evaluate(()=>__probe());assert(p.touchSteer>.2&&p.input.forward);console.log('PASS simultaneous throttle and steering');
await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await page.waitForTimeout(200);p=await page.evaluate(()=>__probe());assert.equal(p.touchSteer,0);assert.equal(p.input.forward,false);assert.equal(p.wheelPointer,null);console.log('PASS touch cancellation');
await page.keyboard.down('ArrowRight');await page.waitForTimeout(100);await page.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await page.evaluate(()=>__probe())).input.right,false);await page.keyboard.up('ArrowRight');console.log('PASS blur releases inputs');
await page.setViewportSize({width:844,height:390});await page.screenshot({path:path.join(out,'race-mobile.png')});await page.goto('http://127.0.0.1:8001/games/f1-racer/race.html?circuit=portoscuro&touch=1');await page.waitForFunction(()=>window.__probe,null,{timeout:60000});await page.waitForTimeout(500);await page.screenshot({path:path.join(out,'race-wet.png')});console.log('Wet',await page.evaluate(()=>__probe()));assert.deepEqual(errors,[]);console.log('PASS dry/wet rendering, no console/runtime errors');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
